/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GenerateBtn: typeof import('./src/features/controls/components/GenerateBtn.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    HorseItem: typeof import('./src/features/horseTrack/components/HorseItem.vue')['default']
    HorseList: typeof import('./src/features/horseList/components/HorseList.vue')['default']
    HorseTrack: typeof import('./src/features/horseTrack/components/HorseTrack.vue')['default']
    HRTable: typeof import('./src/components/shared/HRTable.vue')['default']
    Program: typeof import('./src/features/program/components/Program.vue')['default']
    Result: typeof import('./src/features/result/components/Result.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StartBtn: typeof import('./src/features/controls/components/StartBtn.vue')['default']
  }
}
